# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DayOfferVectorInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_timestamp: datetime=None, end_timestamp: datetime=None, price: float=None, volume: float=None):  # noqa: E501
        """DayOfferVectorInner - a model defined in Swagger

        :param start_timestamp: The start_timestamp of this DayOfferVectorInner.  # noqa: E501
        :type start_timestamp: datetime
        :param end_timestamp: The end_timestamp of this DayOfferVectorInner.  # noqa: E501
        :type end_timestamp: datetime
        :param price: The price of this DayOfferVectorInner.  # noqa: E501
        :type price: float
        :param volume: The volume of this DayOfferVectorInner.  # noqa: E501
        :type volume: float
        """
        self.swagger_types = {
            'start_timestamp': datetime,
            'end_timestamp': datetime,
            'price': float,
            'volume': float
        }

        self.attribute_map = {
            'start_timestamp': 'start_timestamp',
            'end_timestamp': 'end_timestamp',
            'price': 'price',
            'volume': 'volume'
        }
        self._start_timestamp = start_timestamp
        self._end_timestamp = end_timestamp
        self._price = price
        self._volume = volume

    @classmethod
    def from_dict(cls, dikt) -> 'DayOfferVectorInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DayOfferVector_inner of this DayOfferVectorInner.  # noqa: E501
        :rtype: DayOfferVectorInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_timestamp(self) -> datetime:
        """Gets the start_timestamp of this DayOfferVectorInner.


        :return: The start_timestamp of this DayOfferVectorInner.
        :rtype: datetime
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp: datetime):
        """Sets the start_timestamp of this DayOfferVectorInner.


        :param start_timestamp: The start_timestamp of this DayOfferVectorInner.
        :type start_timestamp: datetime
        """

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self) -> datetime:
        """Gets the end_timestamp of this DayOfferVectorInner.


        :return: The end_timestamp of this DayOfferVectorInner.
        :rtype: datetime
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp: datetime):
        """Sets the end_timestamp of this DayOfferVectorInner.


        :param end_timestamp: The end_timestamp of this DayOfferVectorInner.
        :type end_timestamp: datetime
        """

        self._end_timestamp = end_timestamp

    @property
    def price(self) -> float:
        """Gets the price of this DayOfferVectorInner.


        :return: The price of this DayOfferVectorInner.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this DayOfferVectorInner.


        :param price: The price of this DayOfferVectorInner.
        :type price: float
        """

        self._price = price

    @property
    def volume(self) -> float:
        """Gets the volume of this DayOfferVectorInner.


        :return: The volume of this DayOfferVectorInner.
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume: float):
        """Sets the volume of this DayOfferVectorInner.


        :param volume: The volume of this DayOfferVectorInner.
        :type volume: float
        """

        self._volume = volume
