# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DayPriceVectorEuroValues(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, price: float=None, volume: float=None):  # noqa: E501
        """DayPriceVectorEuroValues - a model defined in Swagger

        :param price: The price of this DayPriceVectorEuroValues.  # noqa: E501
        :type price: float
        :param volume: The volume of this DayPriceVectorEuroValues.  # noqa: E501
        :type volume: float
        """
        self.swagger_types = {
            'price': float,
            'volume': float
        }

        self.attribute_map = {
            'price': 'price',
            'volume': 'volume'
        }
        self._price = price
        self._volume = volume

    @classmethod
    def from_dict(cls, dikt) -> 'DayPriceVectorEuroValues':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DayPriceVector_Euro_values of this DayPriceVectorEuroValues.  # noqa: E501
        :rtype: DayPriceVectorEuroValues
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self) -> float:
        """Gets the price of this DayPriceVectorEuroValues.


        :return: The price of this DayPriceVectorEuroValues.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this DayPriceVectorEuroValues.


        :param price: The price of this DayPriceVectorEuroValues.
        :type price: float
        """

        self._price = price

    @property
    def volume(self) -> float:
        """Gets the volume of this DayPriceVectorEuroValues.


        :return: The volume of this DayPriceVectorEuroValues.
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume: float):
        """Sets the volume of this DayPriceVectorEuroValues.


        :param volume: The volume of this DayPriceVectorEuroValues.
        :type volume: float
        """

        self._volume = volume
