# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.day_price_vector_euro_values import DayPriceVectorEuroValues  # noqa: F401,E501
from swagger_server import util


class DayPriceVectorEuro(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, values: List[DayPriceVectorEuroValues]=None, currency: str=None):  # noqa: E501
        """DayPriceVectorEuro - a model defined in Swagger

        :param values: The values of this DayPriceVectorEuro.  # noqa: E501
        :type values: List[DayPriceVectorEuroValues]
        :param currency: The currency of this DayPriceVectorEuro.  # noqa: E501
        :type currency: str
        """
        self.swagger_types = {
            'values': List[DayPriceVectorEuroValues],
            'currency': str
        }

        self.attribute_map = {
            'values': 'values',
            'currency': 'currency'
        }
        self._values = values
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'DayPriceVectorEuro':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DayPriceVector_Euro of this DayPriceVectorEuro.  # noqa: E501
        :rtype: DayPriceVectorEuro
        """
        return util.deserialize_model(dikt, cls)

    @property
    def values(self) -> List[DayPriceVectorEuroValues]:
        """Gets the values of this DayPriceVectorEuro.


        :return: The values of this DayPriceVectorEuro.
        :rtype: List[DayPriceVectorEuroValues]
        """
        return self._values

    @values.setter
    def values(self, values: List[DayPriceVectorEuroValues]):
        """Sets the values of this DayPriceVectorEuro.


        :param values: The values of this DayPriceVectorEuro.
        :type values: List[DayPriceVectorEuroValues]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values

    @property
    def currency(self) -> str:
        """Gets the currency of this DayPriceVectorEuro.


        :return: The currency of this DayPriceVectorEuro.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this DayPriceVectorEuro.


        :param currency: The currency of this DayPriceVectorEuro.
        :type currency: str
        """
        allowed_values = ["€"]  # noqa: E501
        if currency not in allowed_values:
            raise ValueError(
                "Invalid value for `currency` ({0}), must be one of {1}"
                .format(currency, allowed_values)
            )

        self._currency = currency
