# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.flex_offer_data_point_flexibility import FlexOfferDataPointFlexibility  # noqa: F401,E501
from swagger_server import util


class FlexOfferDataPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: str=None, flexibility: List[FlexOfferDataPointFlexibility]=None):  # noqa: E501
        """FlexOfferDataPoint - a model defined in Swagger

        :param timestamp: The timestamp of this FlexOfferDataPoint.  # noqa: E501
        :type timestamp: str
        :param flexibility: The flexibility of this FlexOfferDataPoint.  # noqa: E501
        :type flexibility: List[FlexOfferDataPointFlexibility]
        """
        self.swagger_types = {
            'timestamp': str,
            'flexibility': List[FlexOfferDataPointFlexibility]
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'flexibility': 'flexibility'
        }
        self._timestamp = timestamp
        self._flexibility = flexibility

    @classmethod
    def from_dict(cls, dikt) -> 'FlexOfferDataPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexOfferDataPoint of this FlexOfferDataPoint.  # noqa: E501
        :rtype: FlexOfferDataPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this FlexOfferDataPoint.


        :return: The timestamp of this FlexOfferDataPoint.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this FlexOfferDataPoint.


        :param timestamp: The timestamp of this FlexOfferDataPoint.
        :type timestamp: str
        """

        self._timestamp = timestamp

    @property
    def flexibility(self) -> List[FlexOfferDataPointFlexibility]:
        """Gets the flexibility of this FlexOfferDataPoint.


        :return: The flexibility of this FlexOfferDataPoint.
        :rtype: List[FlexOfferDataPointFlexibility]
        """
        return self._flexibility

    @flexibility.setter
    def flexibility(self, flexibility: List[FlexOfferDataPointFlexibility]):
        """Sets the flexibility of this FlexOfferDataPoint.


        :param flexibility: The flexibility of this FlexOfferDataPoint.
        :type flexibility: List[FlexOfferDataPointFlexibility]
        """

        self._flexibility = flexibility
