# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FlexOfferParamsTimeGranularity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, duration_seconds: int=None):  # noqa: E501
        """FlexOfferParamsTimeGranularity - a model defined in Swagger

        :param id: The id of this FlexOfferParamsTimeGranularity.  # noqa: E501
        :type id: str
        :param duration_seconds: The duration_seconds of this FlexOfferParamsTimeGranularity.  # noqa: E501
        :type duration_seconds: int
        """
        self.swagger_types = {
            'id': str,
            'duration_seconds': int
        }

        self.attribute_map = {
            'id': 'id',
            'duration_seconds': 'duration_seconds'
        }
        self._id = id
        self._duration_seconds = duration_seconds

    @classmethod
    def from_dict(cls, dikt) -> 'FlexOfferParamsTimeGranularity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexOfferParams_time_granularity of this FlexOfferParamsTimeGranularity.  # noqa: E501
        :rtype: FlexOfferParamsTimeGranularity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this FlexOfferParamsTimeGranularity.


        :return: The id of this FlexOfferParamsTimeGranularity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FlexOfferParamsTimeGranularity.


        :param id: The id of this FlexOfferParamsTimeGranularity.
        :type id: str
        """

        self._id = id

    @property
    def duration_seconds(self) -> int:
        """Gets the duration_seconds of this FlexOfferParamsTimeGranularity.


        :return: The duration_seconds of this FlexOfferParamsTimeGranularity.
        :rtype: int
        """
        return self._duration_seconds

    @duration_seconds.setter
    def duration_seconds(self, duration_seconds: int):
        """Sets the duration_seconds of this FlexOfferParamsTimeGranularity.


        :param duration_seconds: The duration_seconds of this FlexOfferParamsTimeGranularity.
        :type duration_seconds: int
        """

        self._duration_seconds = duration_seconds
