# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.flex_asset import FlexAsset  # noqa: F401,E501
from swagger_server.models.flex_offer_params_time_granularity import FlexOfferParamsTimeGranularity  # noqa: F401,E501
from swagger_server.models.location import Location  # noqa: F401,E501
from swagger_server import util


class FlexOfferParams(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, country: str=None, flex_assets: List[FlexAsset]=None, start_datetime: datetime=None, end_datetime: datetime=None, time_granularity: FlexOfferParamsTimeGranularity=None, location: Location=None, store_data: bool=None):  # noqa: E501
        """FlexOfferParams - a model defined in Swagger

        :param country: The country of this FlexOfferParams.  # noqa: E501
        :type country: str
        :param flex_assets: The flex_assets of this FlexOfferParams.  # noqa: E501
        :type flex_assets: List[FlexAsset]
        :param start_datetime: The start_datetime of this FlexOfferParams.  # noqa: E501
        :type start_datetime: datetime
        :param end_datetime: The end_datetime of this FlexOfferParams.  # noqa: E501
        :type end_datetime: datetime
        :param time_granularity: The time_granularity of this FlexOfferParams.  # noqa: E501
        :type time_granularity: FlexOfferParamsTimeGranularity
        :param location: The location of this FlexOfferParams.  # noqa: E501
        :type location: Location
        :param store_data: The store_data of this FlexOfferParams.  # noqa: E501
        :type store_data: bool
        """
        self.swagger_types = {
            'country': str,
            'flex_assets': List[FlexAsset],
            'start_datetime': datetime,
            'end_datetime': datetime,
            'time_granularity': FlexOfferParamsTimeGranularity,
            'location': Location,
            'store_data': bool
        }

        self.attribute_map = {
            'country': 'country',
            'flex_assets': 'flex_assets',
            'start_datetime': 'start_datetime',
            'end_datetime': 'end_datetime',
            'time_granularity': 'time_granularity',
            'location': 'location',
            'store_data': 'store_data'
        }
        self._country = country
        self._flex_assets = flex_assets
        self._start_datetime = start_datetime
        self._end_datetime = end_datetime
        self._time_granularity = time_granularity
        self._location = location
        self._store_data = store_data

    @classmethod
    def from_dict(cls, dikt) -> 'FlexOfferParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexOfferParams of this FlexOfferParams.  # noqa: E501
        :rtype: FlexOfferParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country(self) -> str:
        """Gets the country of this FlexOfferParams.


        :return: The country of this FlexOfferParams.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this FlexOfferParams.


        :param country: The country of this FlexOfferParams.
        :type country: str
        """

        self._country = country

    @property
    def flex_assets(self) -> List[FlexAsset]:
        """Gets the flex_assets of this FlexOfferParams.


        :return: The flex_assets of this FlexOfferParams.
        :rtype: List[FlexAsset]
        """
        return self._flex_assets

    @flex_assets.setter
    def flex_assets(self, flex_assets: List[FlexAsset]):
        """Sets the flex_assets of this FlexOfferParams.


        :param flex_assets: The flex_assets of this FlexOfferParams.
        :type flex_assets: List[FlexAsset]
        """

        self._flex_assets = flex_assets

    @property
    def start_datetime(self) -> datetime:
        """Gets the start_datetime of this FlexOfferParams.


        :return: The start_datetime of this FlexOfferParams.
        :rtype: datetime
        """
        return self._start_datetime

    @start_datetime.setter
    def start_datetime(self, start_datetime: datetime):
        """Sets the start_datetime of this FlexOfferParams.


        :param start_datetime: The start_datetime of this FlexOfferParams.
        :type start_datetime: datetime
        """

        self._start_datetime = start_datetime

    @property
    def end_datetime(self) -> datetime:
        """Gets the end_datetime of this FlexOfferParams.


        :return: The end_datetime of this FlexOfferParams.
        :rtype: datetime
        """
        return self._end_datetime

    @end_datetime.setter
    def end_datetime(self, end_datetime: datetime):
        """Sets the end_datetime of this FlexOfferParams.


        :param end_datetime: The end_datetime of this FlexOfferParams.
        :type end_datetime: datetime
        """

        self._end_datetime = end_datetime

    @property
    def time_granularity(self) -> FlexOfferParamsTimeGranularity:
        """Gets the time_granularity of this FlexOfferParams.


        :return: The time_granularity of this FlexOfferParams.
        :rtype: FlexOfferParamsTimeGranularity
        """
        return self._time_granularity

    @time_granularity.setter
    def time_granularity(self, time_granularity: FlexOfferParamsTimeGranularity):
        """Sets the time_granularity of this FlexOfferParams.


        :param time_granularity: The time_granularity of this FlexOfferParams.
        :type time_granularity: FlexOfferParamsTimeGranularity
        """

        self._time_granularity = time_granularity

    @property
    def location(self) -> Location:
        """Gets the location of this FlexOfferParams.


        :return: The location of this FlexOfferParams.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location: Location):
        """Sets the location of this FlexOfferParams.


        :param location: The location of this FlexOfferParams.
        :type location: Location
        """

        self._location = location

    @property
    def store_data(self) -> bool:
        """Gets the store_data of this FlexOfferParams.


        :return: The store_data of this FlexOfferParams.
        :rtype: bool
        """
        return self._store_data

    @store_data.setter
    def store_data(self, store_data: bool):
        """Sets the store_data of this FlexOfferParams.


        :param store_data: The store_data of this FlexOfferParams.
        :type store_data: bool
        """

        self._store_data = store_data
