# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FlexOfferDataPointFlexibility(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, price_euro_per_kw: float=None, quantity_kw: float=None, direction: str=None, minquantity: float=None):  # noqa: E501
        """FlexOfferDataPointFlexibility - a model defined in Swagger

        :param price_euro_per_kw: The price_euro_per_kw of this FlexOfferDataPointFlexibility.  # noqa: E501
        :type price_euro_per_kw: float
        :param quantity_kw: The quantity_kw of this FlexOfferDataPointFlexibility.  # noqa: E501
        :type quantity_kw: float
        :param direction: The direction of this FlexOfferDataPointFlexibility.  # noqa: E501
        :type direction: str
        :param minquantity: The minquantity of this FlexOfferDataPointFlexibility.  # noqa: E501
        :type minquantity: float
        """
        self.swagger_types = {
            'price_euro_per_kw': float,
            'quantity_kw': float,
            'direction': str,
            'minquantity': float
        }

        self.attribute_map = {
            'price_euro_per_kw': 'price_euro_per_kw',
            'quantity_kw': 'quantity_kw',
            'direction': 'direction',
            'minquantity': 'minquantity'
        }
        self._price_euro_per_kw = price_euro_per_kw
        self._quantity_kw = quantity_kw
        self._direction = direction
        self._minquantity = minquantity

    @classmethod
    def from_dict(cls, dikt) -> 'FlexOfferDataPointFlexibility':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexOfferDataPoint_flexibility of this FlexOfferDataPointFlexibility.  # noqa: E501
        :rtype: FlexOfferDataPointFlexibility
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price_euro_per_kw(self) -> float:
        """Gets the price_euro_per_kw of this FlexOfferDataPointFlexibility.


        :return: The price_euro_per_kw of this FlexOfferDataPointFlexibility.
        :rtype: float
        """
        return self._price_euro_per_kw

    @price_euro_per_kw.setter
    def price_euro_per_kw(self, price_euro_per_kw: float):
        """Sets the price_euro_per_kw of this FlexOfferDataPointFlexibility.


        :param price_euro_per_kw: The price_euro_per_kw of this FlexOfferDataPointFlexibility.
        :type price_euro_per_kw: float
        """

        self._price_euro_per_kw = price_euro_per_kw

    @property
    def quantity_kw(self) -> float:
        """Gets the quantity_kw of this FlexOfferDataPointFlexibility.


        :return: The quantity_kw of this FlexOfferDataPointFlexibility.
        :rtype: float
        """
        return self._quantity_kw

    @quantity_kw.setter
    def quantity_kw(self, quantity_kw: float):
        """Sets the quantity_kw of this FlexOfferDataPointFlexibility.


        :param quantity_kw: The quantity_kw of this FlexOfferDataPointFlexibility.
        :type quantity_kw: float
        """

        self._quantity_kw = quantity_kw

    @property
    def direction(self) -> str:
        """Gets the direction of this FlexOfferDataPointFlexibility.


        :return: The direction of this FlexOfferDataPointFlexibility.
        :rtype: str
        """
        return self._direction

    @direction.setter
    def direction(self, direction: str):
        """Sets the direction of this FlexOfferDataPointFlexibility.


        :param direction: The direction of this FlexOfferDataPointFlexibility.
        :type direction: str
        """

        self._direction = direction

    @property
    def minquantity(self) -> float:
        """Gets the minquantity of this FlexOfferDataPointFlexibility.


        :return: The minquantity of this FlexOfferDataPointFlexibility.
        :rtype: float
        """
        return self._minquantity

    @minquantity.setter
    def minquantity(self, minquantity: float):
        """Sets the minquantity of this FlexOfferDataPointFlexibility.


        :param minquantity: The minquantity of this FlexOfferDataPointFlexibility.
        :type minquantity: float
        """

        self._minquantity = minquantity
