# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class JobSubmitted(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, job_id: str=None, href: str=None):  # noqa: E501
        """JobSubmitted - a model defined in Swagger

        :param job_id: The job_id of this JobSubmitted.  # noqa: E501
        :type job_id: str
        :param href: The href of this JobSubmitted.  # noqa: E501
        :type href: str
        """
        self.swagger_types = {
            'job_id': str,
            'href': str
        }

        self.attribute_map = {
            'job_id': 'job_id',
            'href': 'href'
        }
        self._job_id = job_id
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'JobSubmitted':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobSubmitted of this JobSubmitted.  # noqa: E501
        :rtype: JobSubmitted
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> str:
        """Gets the job_id of this JobSubmitted.


        :return: The job_id of this JobSubmitted.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this JobSubmitted.


        :param job_id: The job_id of this JobSubmitted.
        :type job_id: str
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def href(self) -> str:
        """Gets the href of this JobSubmitted.


        :return: The href of this JobSubmitted.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this JobSubmitted.


        :param href: The href of this JobSubmitted.
        :type href: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href
