# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PowerVectorItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_timestamp: datetime=None, end_timestamp: datetime=None, power: float=None):  # noqa: E501
        """PowerVectorItem - a model defined in Swagger

        :param start_timestamp: The start_timestamp of this PowerVectorItem.  # noqa: E501
        :type start_timestamp: datetime
        :param end_timestamp: The end_timestamp of this PowerVectorItem.  # noqa: E501
        :type end_timestamp: datetime
        :param power: The power of this PowerVectorItem.  # noqa: E501
        :type power: float
        """
        self.swagger_types = {
            'start_timestamp': datetime,
            'end_timestamp': datetime,
            'power': float
        }

        self.attribute_map = {
            'start_timestamp': 'start_timestamp',
            'end_timestamp': 'end_timestamp',
            'power': 'power'
        }
        self._start_timestamp = start_timestamp
        self._end_timestamp = end_timestamp
        self._power = power

    @classmethod
    def from_dict(cls, dikt) -> 'PowerVectorItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PowerVectorItem of this PowerVectorItem.  # noqa: E501
        :rtype: PowerVectorItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_timestamp(self) -> datetime:
        """Gets the start_timestamp of this PowerVectorItem.


        :return: The start_timestamp of this PowerVectorItem.
        :rtype: datetime
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp: datetime):
        """Sets the start_timestamp of this PowerVectorItem.


        :param start_timestamp: The start_timestamp of this PowerVectorItem.
        :type start_timestamp: datetime
        """

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self) -> datetime:
        """Gets the end_timestamp of this PowerVectorItem.


        :return: The end_timestamp of this PowerVectorItem.
        :rtype: datetime
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp: datetime):
        """Sets the end_timestamp of this PowerVectorItem.


        :param end_timestamp: The end_timestamp of this PowerVectorItem.
        :type end_timestamp: datetime
        """

        self._end_timestamp = end_timestamp

    @property
    def power(self) -> float:
        """Gets the power of this PowerVectorItem.


        :return: The power of this PowerVectorItem.
        :rtype: float
        """
        return self._power

    @power.setter
    def power(self, power: float):
        """Sets the power of this PowerVectorItem.


        :param power: The power of this PowerVectorItem.
        :type power: float
        """

        self._power = power
