# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PricingParamsFlexContracts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, id: float=None, gamma: float=None):  # noqa: E501
        """PricingParamsFlexContracts - a model defined in Swagger

        :param name: The name of this PricingParamsFlexContracts.  # noqa: E501
        :type name: str
        :param id: The id of this PricingParamsFlexContracts.  # noqa: E501
        :type id: float
        :param gamma: The gamma of this PricingParamsFlexContracts.  # noqa: E501
        :type gamma: float
        """
        self.swagger_types = {
            'name': str,
            'id': float,
            'gamma': float
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'gamma': 'gamma'
        }
        self._name = name
        self._id = id
        self._gamma = gamma

    @classmethod
    def from_dict(cls, dikt) -> 'PricingParamsFlexContracts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PricingParams_flex_contracts of this PricingParamsFlexContracts.  # noqa: E501
        :rtype: PricingParamsFlexContracts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this PricingParamsFlexContracts.


        :return: The name of this PricingParamsFlexContracts.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PricingParamsFlexContracts.


        :param name: The name of this PricingParamsFlexContracts.
        :type name: str
        """

        self._name = name

    @property
    def id(self) -> float:
        """Gets the id of this PricingParamsFlexContracts.


        :return: The id of this PricingParamsFlexContracts.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this PricingParamsFlexContracts.


        :param id: The id of this PricingParamsFlexContracts.
        :type id: float
        """

        self._id = id

    @property
    def gamma(self) -> float:
        """Gets the gamma of this PricingParamsFlexContracts.


        :return: The gamma of this PricingParamsFlexContracts.
        :rtype: float
        """
        return self._gamma

    @gamma.setter
    def gamma(self, gamma: float):
        """Sets the gamma of this PricingParamsFlexContracts.


        :param gamma: The gamma of this PricingParamsFlexContracts.
        :type gamma: float
        """

        self._gamma = gamma
