# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PricingParamsCallback(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, headers: Dict[str, str]=None):  # noqa: E501
        """PricingParamsCallback - a model defined in Swagger

        :param url: The url of this PricingParamsCallback.  # noqa: E501
        :type url: str
        :param headers: The headers of this PricingParamsCallback.  # noqa: E501
        :type headers: Dict[str, str]
        """
        self.swagger_types = {
            'url': str,
            'headers': Dict[str, str]
        }

        self.attribute_map = {
            'url': 'url',
            'headers': 'headers'
        }
        self._url = url
        self._headers = headers

    @classmethod
    def from_dict(cls, dikt) -> 'PricingParamsCallback':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PricingParams_callback of this PricingParamsCallback.  # noqa: E501
        :rtype: PricingParamsCallback
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this PricingParamsCallback.


        :return: The url of this PricingParamsCallback.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this PricingParamsCallback.


        :param url: The url of this PricingParamsCallback.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def headers(self) -> Dict[str, str]:
        """Gets the headers of this PricingParamsCallback.


        :return: The headers of this PricingParamsCallback.
        :rtype: Dict[str, str]
        """
        return self._headers

    @headers.setter
    def headers(self, headers: Dict[str, str]):
        """Sets the headers of this PricingParamsCallback.


        :param headers: The headers of this PricingParamsCallback.
        :type headers: Dict[str, str]
        """

        self._headers = headers
