# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RevenueVectorItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_timestamp: datetime=None, end_timestamp: datetime=None, revenue: float=None):  # noqa: E501
        """RevenueVectorItem - a model defined in Swagger

        :param start_timestamp: The start_timestamp of this RevenueVectorItem.  # noqa: E501
        :type start_timestamp: datetime
        :param end_timestamp: The end_timestamp of this RevenueVectorItem.  # noqa: E501
        :type end_timestamp: datetime
        :param revenue: The revenue of this RevenueVectorItem.  # noqa: E501
        :type revenue: float
        """
        self.swagger_types = {
            'start_timestamp': datetime,
            'end_timestamp': datetime,
            'revenue': float
        }

        self.attribute_map = {
            'start_timestamp': 'start_timestamp',
            'end_timestamp': 'end_timestamp',
            'revenue': 'revenue'
        }
        self._start_timestamp = start_timestamp
        self._end_timestamp = end_timestamp
        self._revenue = revenue

    @classmethod
    def from_dict(cls, dikt) -> 'RevenueVectorItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RevenueVectorItem of this RevenueVectorItem.  # noqa: E501
        :rtype: RevenueVectorItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_timestamp(self) -> datetime:
        """Gets the start_timestamp of this RevenueVectorItem.


        :return: The start_timestamp of this RevenueVectorItem.
        :rtype: datetime
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp: datetime):
        """Sets the start_timestamp of this RevenueVectorItem.


        :param start_timestamp: The start_timestamp of this RevenueVectorItem.
        :type start_timestamp: datetime
        """

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self) -> datetime:
        """Gets the end_timestamp of this RevenueVectorItem.


        :return: The end_timestamp of this RevenueVectorItem.
        :rtype: datetime
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp: datetime):
        """Sets the end_timestamp of this RevenueVectorItem.


        :param end_timestamp: The end_timestamp of this RevenueVectorItem.
        :type end_timestamp: datetime
        """

        self._end_timestamp = end_timestamp

    @property
    def revenue(self) -> float:
        """Gets the revenue of this RevenueVectorItem.


        :return: The revenue of this RevenueVectorItem.
        :rtype: float
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue: float):
        """Sets the revenue of this RevenueVectorItem.


        :param revenue: The revenue of this RevenueVectorItem.
        :type revenue: float
        """

        self._revenue = revenue
