openapi: 3.0.3
info:
  title: Flexgrid ATP API
  description: The Automated Trading Platform (ATP) of the flexgrid project
  termsOfService: https://atp.flexgrid-project.eu/terms/
  contact:
    name: Dimitros J. Vergados
    url: https://flexgrid-project.eu
  license:
    name: BSD
    url: https://github.com/pyeve/eve-swagger/blob/master/LICENSE
  version: "1.0"
paths:
  /scenarios:
    post:
      summary: Initiates a simulation scenario
      requestBody:
        $ref: "#/components/requestBodies/ScenarioParams"
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScenarioResult"
        "400":
          description: bad request
      tags:
        - Scenario
      security:
        - MyTokenAuth: []

tags:
  - name: Prosumer
servers:
  - url: http://localhost:8080/
components:
  requestBodies:
    ScenarioParams:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ScenarioParams"
        application/xml:
          schema:
            $ref: "#/components/schemas/ScenarioParams"
      required: true
  securitySchemes:
    MyTokenAuth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://db.flexgrid-project.eu/oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: https://db.flexgrid-project.eu/authorization
          scopes:
            post_scenario: post a scenario

  schemas:
    ScenarioParams:
      type: object
      required:
        - sdate
        - country
        - markets
        - storage_units
      properties:
        sdate:
          type: string
          format: date
          example: "2020-10-16"
        country:
          type: string
          example: "GR"
        markets:
          type: array
          minItems: 1
          items:
            type: string
            example: "day_ahead"
        storage_units:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/StorageUnit"

    StorageUnit:
      type: object
      required:
        - location
      properties:
        power_capacity_KW:
          type: number
          minimum: 0
        energy_capacity_KWh:
          type: number
          minimum: 0
        inefficiency_rate_per_cent:
          type: number
          minimum: 0
          maximum: 1
        initial_final_SoC_per_cent:
          type: number
          minimum: 0
          maximum: 1
        location:
          $ref: "#/components/schemas/Location"

    Location:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: objectid
        name:
          type: string

    ScenarioResult:
      type: object
      required:
        - sdate
        - flex_offer
        - revenues
      properties:
        sdate:
          type: string
          format: date
          example: "2020-10-16"
        flex_offer:
          type: object
          properties:
            day_ahead_market_offer:
              $ref: "#/components/schemas/DayOfferVector_Euro_MWh"
            reserve_market_offer:
              type: object
              required:
                - values
                - price_unit
                - volume_unit
              properties:
                values:
                  $ref: "#/components/schemas/DayOfferVector"
                price_unit:
                  type: string
                  enum:
                    - "(€/MWh)^2"
                volume_unit:
                  type: string
                  enum:
                    - "MWh^2"
            d-LMPs:
              $ref: "#/components/schemas/DayOfferVector_Euro_MWh"
            q-LMPs:
              type: object
              required:
                - values
                - price_unit
                - volume_unit
              properties:
                values:
                  $ref: "#/components/schemas/DayOfferVector"
                price_unit:
                  type: string
                  enum:
                    - "€/MVar"
                volume_unit:
                  type: string
                  enum:
                    - "MVar"
            balancing_market_offer:
              $ref: "#/components/schemas/DayOfferVector_Euro_MWh"
        revenues:
          type: object
          properties:
            day_ahead_market_revenues:
              $ref: "#/components/schemas/DayPriceVector_Euro"
            reserve_market_revenues:
              $ref: "#/components/schemas/DayPriceVector_Euro"
            d-LMPs:
              $ref: "#/components/schemas/DayPriceVector_Euro"
            q-LMPs:
              $ref: "#/components/schemas/DayPriceVector_Euro"
            balancing_market_revenues:
              $ref: "#/components/schemas/DayPriceVector_Euro"

    DayOfferVector:
      type: array
      minItems: 23
      maxItems: 25
      # example: [113.3, 12.4, 5.5, 225.3,  2.6, 21.1,
      #           21.0, 24.9, 24.2, 1.45, 15.4, 15.2,
      #           15.1, 1.45, 5.54, 5.34, 6.45, 8.45,
      #           8.45, 3.34, 1.34, 2.45, 7.14, 9.53 ]
      items:
        $ref: "#/components/schemas/DayOfferVectorItem"

    DayOfferVectorItem:
      type: object
      properties:
        price:
          type: number
          format: currency
        volume:
          type: number

    DayOfferVector_Euro_MWh:
      type: object
      required:
        - values
        - price_unit
        - volume_unit
      properties:
        values:
          $ref: "#/components/schemas/DayOfferVector"
        price_unit:
          type: string
          enum:
            - "€/MWh"
        volume_unit:
          type: string
          enum:
            - "MWh"

    DayPriceVector_Euro:
      type: object
      required:
        - values
        - currency
      properties:
        values:
          type: array
          minItems: 23
          maxItems: 25
          example:
            [
              113.3,
              12.4,
              5.5,
              225.3,
              2.6,
              21.1,
              21.0,
              24.9,
              24.2,
              1.45,
              15.4,
              15.2,
              15.1,
              1.45,
              5.54,
              5.34,
              6.45,
              8.45,
              8.45,
              3.34,
              1.34,
              2.45,
              7.14,
              9.53,
            ]
          items:
            type: object
            properties:
              price:
                type: number
                format: currency
              volume:
                type: number
        currency:
          type: string
          enum:
            - "€"
