openapi: 3.0.3
info:
  title: Flexgrid ATP API
  description: The Automated Trading Platform (ATP) of the flexgrid project
  termsOfService: https://atp.flexgrid-project.eu/terms/
  contact:
    name: Dimitros J. Vergados
    url: https://flexgrid-project.eu
  license:
    name: BSD
    url: https://github.com/pyeve/eve-swagger/blob/master/LICENSE
  version: "1.0"
servers:
- url: http://localhost:8080/
tags:
- name: Prosumer
paths:
  /scenarios:
    post:
      tags:
      - Scenario
      summary: Initiates a simulation scenario
      operationId: scenarios_post
      requestBody:
        $ref: '#/components/requestBodies/ScenarioParams'
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioResult'
        "400":
          description: bad request
      security:
      - MyTokenAuth: []
      x-openapi-router-controller: swagger_server.controllers.scenario_controller
components:
  schemas:
    ScenarioParams:
      required:
      - country
      - markets
      - sdate
      - storage_units
      type: object
      properties:
        sdate:
          type: string
          format: date
          example: 2020-10-16
        country:
          type: string
          example: GR
        markets:
          minItems: 1
          type: array
          items:
            type: string
            example: day_ahead
        storage_units:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/StorageUnit'
    StorageUnit:
      required:
      - location
      type: object
      properties:
        power_capacity_KW:
          minimum: 0
          type: number
        energy_capacity_KWh:
          minimum: 0
          type: number
        inefficiency_rate_per_cent:
          maximum: 1
          minimum: 0
          type: number
        initial_final_SoC_per_cent:
          maximum: 1
          minimum: 0
          type: number
        location:
          $ref: '#/components/schemas/Location'
    Location:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: objectid
        name:
          type: string
    ScenarioResult:
      required:
      - flex_offer
      - revenues
      - sdate
      type: object
      properties:
        sdate:
          type: string
          format: date
          example: 2020-10-16
        flex_offer:
          $ref: '#/components/schemas/ScenarioResult_flex_offer'
        revenues:
          $ref: '#/components/schemas/ScenarioResult_revenues'
      example:
        sdate: 2020-10-16T00:00:00.000+0000
        flex_offer:
          balancing_market_offer: null
          q-LMPs:
            price_unit: €/MVar
            volume_unit: MVar
            values: null
          reserve_market_offer:
            price_unit: (€/MWh)^2
            volume_unit: MWh^2
            values: null
          day_ahead_market_offer:
            price_unit: €/MWh
            volume_unit: MWh
            values:
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
          d-LMPs: null
        revenues:
          q-LMPs: null
          balancing_market_revenues: null
          reserve_market_revenues: null
          day_ahead_market_revenues:
            values:
            - 113.3
            - 12.4
            - 5.5
            - 225.3
            - 2.6
            - 21.1
            - 21.0
            - 24.9
            - 24.2
            - 1.45
            - 15.4
            - 15.2
            - 15.1
            - 1.45
            - 5.54
            - 5.34
            - 6.45
            - 8.45
            - 8.45
            - 3.34
            - 1.34
            - 2.45
            - 7.14
            - 9.53
            currency: €
          d-LMPs: null
    DayOfferVector:
      maxItems: 25
      minItems: 23
      type: array
      items:
        $ref: '#/components/schemas/DayOfferVectorItem'
    DayOfferVectorItem:
      type: object
      properties:
        price:
          type: number
          format: currency
        volume:
          type: number
      example:
        volume: 6.027456183070403
        price: 0.8008281904610115
    DayOfferVectorEuroMWh:
      required:
      - price_unit
      - values
      - volume_unit
      type: object
      properties:
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh
        volume_unit:
          type: string
          enum:
          - MWh
      example:
        price_unit: €/MWh
        volume_unit: MWh
        values:
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
    DayPriceVector_Euro:
      required:
      - currency
      - values
      type: object
      properties:
        values:
          maxItems: 25
          minItems: 23
          type: array
          example:
          - 113.3
          - 12.4
          - 5.5
          - 225.3
          - 2.6
          - 21.1
          - 21.0
          - 24.9
          - 24.2
          - 1.45
          - 15.4
          - 15.2
          - 15.1
          - 1.45
          - 5.54
          - 5.34
          - 6.45
          - 8.45
          - 8.45
          - 3.34
          - 1.34
          - 2.45
          - 7.14
          - 9.53
          items:
            $ref: '#/components/schemas/DayPriceVector_Euro_values'
        currency:
          type: string
          enum:
          - €
      example:
        values:
        - 113.3
        - 12.4
        - 5.5
        - 225.3
        - 2.6
        - 21.1
        - 21.0
        - 24.9
        - 24.2
        - 1.45
        - 15.4
        - 15.2
        - 15.1
        - 1.45
        - 5.54
        - 5.34
        - 6.45
        - 8.45
        - 8.45
        - 3.34
        - 1.34
        - 2.45
        - 7.14
        - 9.53
        currency: €
    Price_In_Euro:
      required:
      - currency
      - value
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
          enum:
          - €
      example:
        value: 113.3
        currency: €
    DayOfferVectorEuroMWh2:
      required:
      - price_unit
      - values
      - volume_unit
      type: object
      properties:
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh^2
        volume_unit:
          type: string
          enum:
          - MWh^2
      example:
        price_unit: (€/MWh)^2
        volume_unit: MWh^2
        values: null
    FlexOfferDLMPs:
      type: array
      items:
        type: FlexOfferDLMPsItem
    FlexOfferDLMPsItem:
      required:
      - price_unit
      - storage_unit
      - values
      - volume_unit
      type: object
      properties:
        storage_unit:
          type: string
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh
        volume_unit:
          type: string
          enum:
          - MWh
    FlexOfferQLMPs:
      type: array
      items:
        type: FlexOfferQLMPsItem
    FlexOfferQLMPsItem:
      required:
      - price_unit
      - storage_unit
      - values
      - volume_unit
      type: object
      properties:
        storage_unit:
          type: string
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MVar
        volume_unit:
          type: string
          enum:
          - MVar
    ScenarioResult_flex_offer:
      type: object
      properties:
        day_ahead_market_offer:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
        reserve_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        reserve_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        d-LMPs:
          $ref: '#/components/schemas/FlexOfferDLMPs'
        q-LMPs:
          $ref: '#/components/schemas/FlexOfferQLMPs'
        balancing_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
        balancing_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
    ScenarioResult_revenues:
      type: object
      properties:
        day_ahead_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        reserve_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        flexibility_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        balancing_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
    DayPriceVector_Euro_values:
      type: object
      properties:
        price:
          type: number
          format: currency
        volume:
          type: number
  requestBodies:
    ScenarioParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ScenarioParams'
      required: true
  securitySchemes:
    MyTokenAuth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://db.flexgrid-project.eu/oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: https://db.flexgrid-project.eu/authorization
          scopes:
            post_scenario: post a scenario
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_MyTokenAuth
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_MyTokenAuth

