openapi: 3.0.3
info:
  title: Flexgrid ATP API
  description: The Automated Trading Platform (ATP) of the flexgrid project
  termsOfService: https://atp.flexgrid-project.eu/terms/
  contact:
    name: Dimitros J. Vergados
    url: https://flexgrid-project.eu
  license:
    name: BSD
    url: https://github.com/pyeve/eve-swagger/blob/master/LICENSE
  version: "1.0"
servers:
- url: http://localhost:8080/
tags:
- name: Prosumer
paths:
  /stacked_revenues:
    post:
      tags:
      - StackedRevenues (UCS 2.3)
      summary: Initiates a simulation scenario for Stacked Revenues maximization
      operationId: stacked_revenues_post
      requestBody:
        $ref: '#/components/requestBodies/StackedRevenuesParams'
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StackedRevenuesResult'
        "400":
          description: bad request
      security:
      - MyTokenAuth: []
      x-openapi-router-controller: swagger_server.controllers.stacked_revenues_controller
  /flex_offers:
    post:
      tags:
        - FlexOffers (UCS 4.3)
      summary: Creates a Flexibility Offser (FlexOffer) based of FlexAssets
      operationId: flex_offers_post
      requestBody:
        $ref: '#/components/requestBodies/FlexOfferParams'
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlexOfferResult'
        "400":
          description: bad request
      security:
      - MyTokenAuth: []
      x-openapi-router-controller: swagger_server.controllers.flex_offers_controller
  /pricing:
    post:
      tags:
        - Pricing (UCS 4.2)
      summary: Creates an evaluation of various pricing mechanisms
      operationId: pricing_post
      requestBody:
        $ref: '#/components/requestBodies/PricingParams'
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PricingResult'
        "400":
          description: bad request
      security:
      - MyTokenAuth: []
      x-openapi-router-controller: swagger_server.controllers.pricing_controller


components:
  schemas:
    StackedRevenuesParams:
      required:
      - country
      - markets
      - sdate
      - storage_units
      type: object
      properties:
        sdate:
          type: string
          format: date
        country:
          type: string
        markets:
          minItems: 1
          type: array
          items:
            type: string
        storage_units:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/StorageUnit'

    StackedRevenuesResult:
      required:
      - flex_offer
      - revenues
      - sdate
      type: object
      properties:
        sdate:
          type: string
          format: date
        flex_offer:
          $ref: '#/components/schemas/FlexOffer'
        revenues:
          $ref: '#/components/schemas/StackedRevenuesResultRevenues'


    FlexOfferParams:
      type: object
      properties:
        country:
          type: string
        flex_assets:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/FlexAsset'
        start_datetime:
          type: string
          format: date-time
        end_datetime:
          type: string
          format: date-time
        time_granularity:
          type: object
          properties:
            id:
              type: string
            duration_seconds:
              type: integer
        location:
          $ref: '#/components/schemas/Location'
        store_data:
          type: boolean

    FlexOfferResult:
      type: object
      properties:
        reserve_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        reserve_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        expected_revenues:
          type: object
          properties:
            currecy:
              type: string
            revenue_vector:  
              $ref: '#/components/schemas/RevenueVector'


    PricingParams:
      type: object
      properties:
        country:
          type: string
        start_datetime:
          type: string
          format: date-time
        end_datetime:
          type: string
          format: date-time
        time_granularity:
          type: object
          properties:
            id:
              type: string
            duration_seconds:
              type: integer
        time_frame_id:
          type: string
        flex_request:
          $ref: '#/components/schemas/FlexOffer'    
        flex_assets:
          type: array
          items: 
            $ref: '#/components/schemas/FlexAsset'
        storage_units:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/StorageUnit'
        curtailable_loads:
          type: array
          items:
            $ref: '#/components/schemas/CurtailableLoad'
        flex_contracts:
          type: array
          items:
            $ref: '#/components/schemas/FlexContract'
        profit_margin:
          type: number
        store_data:
          type: boolean
        
    PricingResult:
      type: object
      properties:
        flex_contracts:
          type: array
          items:
            type: object
            properties:
              flex_contract:
                $ref: '#/components/schemas/FlexContract'
              flexibility_revenues:
                type: object
                properties:
                  currecy:
                    type: string
                  revenue_vector:  
                    $ref: '#/components/schemas/RevenueVector'
              aggregated_user_welfare:
                type: object
                properties:
                  currecy:
                    type: string
                  welfare_vector:  
                    $ref: '#/components/schemas/RevenueVector'
              flexibility:
                $ref: '#/components/schemas/FlexOffer'

        users:
          type: array
          items:
            type: object
            properties:
              currecy:
                type: string
              welfare_vector:  
                $ref: '#/components/schemas/RevenueVector'
          
                  
    FlexAsset:
      type: object
      properties:
        consumer_id:
          type: string
        reserve_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        reserve_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        location:
          $ref: '#/components/schemas/Location'

    CurtailableLoad:
      type: object
      properties:
        consumer_id:
          type: string
        unit:
           type: string
           enum :
             - 'KW'
        power_vector:
          $ref: '#/components/schemas/PowerVector'
        location:
          $ref: '#/components/schemas/Location'


    FlexContract:
      type: object
      properties:
        name:
          type: string
        id:
          type: number
        gamma:
          type: number

    StorageUnit:
      required:
      - location
      type: object
      properties:
        power_capacity_KW:
          minimum: 0
          type: number
        energy_capacity_KWh:
          minimum: 0
          type: number
        inefficiency_rate_per_cent:
          maximum: 1
          minimum: 0
          type: number
        initial_final_SoC_per_cent:
          maximum: 1
          minimum: 0
          type: number
        location:
          $ref: '#/components/schemas/Location'
    Location:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: objectid
        name:
          type: string


    DayOfferVector:
      maxItems: 25
      minItems: 23
      type: array
      items:
        $ref: '#/components/schemas/DayOfferVectorItem'
        
        
    DayOfferVectorItem:
      type: object
      properties:
        start_timestamp:
          type: string
          format: date-time
        end_timestamp:
          type: string
          format: date-time
        price:
          type: number
          format: currency
        volume:
          type: number

    RevenueVector:
      type: array
      items:
        $ref: '#/components/schemas/RevenueVectorItem'
    RevenueVectorItem:
      type: object
      properties:
        start_timestamp:
          type: string
          format: date-time
        end_timestamp:
          type: string
          format: date-time
        revenue:
          type: number
          format: currency


    PowerVector:
      type: array
      items:
        $ref: '#/components/schemas/PowerVectorItem'
    PowerVectorItem:
      type: object
      properties:
        start_timestamp:
          type: string
          format: date-time
        end_timestamp:
          type: string
          format: date-time
        power:
          type: number
      
    DayOfferVectorEuroMWh:
      required:
      - price_unit
      - values
      - volume_unit
      type: object
      properties:
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh
        volume_unit:
          type: string
          enum:
          - MWh
    Price_In_Euro:
      required:
      - currency
      - value
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
          enum:
          - €
    DayOfferVectorEuroMWh2:
      required:
      - price_unit
      - values
      - volume_unit
      type: object
      properties:
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh^2
        volume_unit:
          type: string
          enum:
          - MWh^2
    FlexOfferDLMPs:
      type: array
      items:
        type: array
        items:
          $ref: '#/components/schemas/FlexOfferDLMPsItem'
    FlexOfferDLMPsItem:
      required:
      - price_unit
      - storage_unit
      - values
      - volume_unit
      type: object
      properties:
        storage_unit:
          type: string
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh
        volume_unit:
          type: string
          enum:
          - MWh
    FlexOfferQLMPs:
      type: array
      items:
        type: array
        items:
          $ref: '#/components/schemas/FlexOfferQLMPsItem'
    FlexOfferQLMPsItem:
      required:
      - price_unit
      - storage_unit
      - values
      - volume_unit
      type: object
      properties:
        storage_unit:
          type: string
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MVar
        volume_unit:
          type: string
          enum:
          - MVar
    FlexOffer:
      type: object
      properties:
        day_ahead_market_offer:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
        reserve_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        reserve_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        d-LMPs:
          $ref: '#/components/schemas/FlexOfferDLMPs'
        q-LMPs:
          $ref: '#/components/schemas/FlexOfferQLMPs'
        balancing_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
        balancing_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
    StackedRevenuesResultRevenues:
      type: object
      properties:
        day_ahead_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        reserve_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        flexibility_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        balancing_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
  requestBodies:
    StackedRevenuesParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StackedRevenuesParams'
      required: true
    FlexOfferParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FlexOfferParams'

    PricingParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PricingParams'

  securitySchemes:
    MyTokenAuth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://db.flexgrid-project.eu/oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: https://db.flexgrid-project.eu/authorization
          scopes:
            post_stacked_revenues: post a stacked revenues scenario
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_MyTokenAuth
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_MyTokenAuth

